teleop_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    baud_rate: 115200
    max_linear: 0.5  # m/s
    max_angular: 1.57  # rad/s
    wheel_base: 0.3  # meters
    max_motor_speed: 255  # PWM value
