sonar_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB1"
    baud_rate: 115200
    frame_id: "sonar_link"
    min_range: 0.02  # meters (2 cm)
    max_range: 4.0   # meters (400 cm)
    field_of_view: 0.1  # radians
    publish_rate: 10.0  # Hz
