version: "3.8"

services:
  robot-sonar:
    image: robot-sonar:latest
    container_name: robot-sonar
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - /dev:/dev
    privileged: true
    restart: unless-stopped

  robot-odometry:
    image: robot-odometry:latest
    container_name: robot-odometry
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - /dev:/dev
    privileged: true
    restart: unless-stopped

  robot-teleop:
    image: robot-teleop:latest
    container_name: robot-teleop
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/fastdds_config.xml
      - ROS_DISABLE_LOANED_MESSAGES=1
      - ROS_LOCALHOST_ONLY=0
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
    volumes:
      - /dev:/dev
    privileged: true
    restart: unless-stopped

  robot-lidar:
    image: robot-lidar:latest
    container_name: robot-lidar
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyS5
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - /dev:/dev
    privileged: true
    restart: unless-stopped
