version: "3.8"

services:
  # ROS2 Master/DDS Discovery
  ros2-daemon:
    image: ros:humble
    container_name: ros2-daemon
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/fastdds_config.xml
      - ROS_DISABLE_LOANED_MESSAGES=1
      - ROS_LOCALHOST_ONLY=0
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
    command: ros2 daemon start
    restart: unless-stopped

  robot-sonar:
    build:
      context: ./src/robot_sonar
      dockerfile: Dockerfile
    container_name: robot-sonar
    network_mode: host
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/fastdds_config.xml
      - ROS_DISABLE_LOANED_MESSAGES=1
      - ROS_LOCALHOST_ONLY=0
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
    volumes:
      - /dev:/dev
    privileged: true
    restart: unless-stopped
    depends_on:
      - ros2-daemon

  robot-odometry:
    build:
      context: ./src/robot_odometry
      dockerfile: Dockerfile
    container_name: robot-odometry
    network_mode: host
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/fastdds_config.xml
      - ROS_DISABLE_LOANED_MESSAGES=1
      - ROS_LOCALHOST_ONLY=0
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
    volumes:
      - /dev:/dev
    privileged: true
    restart: unless-stopped
    depends_on:
      - ros2-daemon

  robot-lidar:
    build:
      context: ./src/lds01rr_lidar_ros2
      dockerfile: Dockerfile
    container_name: robot-lidar
    network_mode: host
    devices:
      - /dev/ttyS5:/dev/ttyS5
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/fastdds_config.xml
      - ROS_DISABLE_LOANED_MESSAGES=1
      - ROS_LOCALHOST_ONLY=0
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
    volumes:
      - /dev:/dev
    privileged: true
    restart: unless-stopped
    depends_on:
      - ros2-daemon

  robot-teleop:
    build:
      context: ./src/robot_teleop
      dockerfile: Dockerfile
    container_name: robot-teleop
    network_mode: host
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/fastdds_config.xml
      - ROS_DISABLE_LOANED_MESSAGES=1
      - ROS_LOCALHOST_ONLY=0
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
    command: ros2 run robot_teleop teleop_node
    volumes:
      - /dev:/dev
    privileged: true
    restart: unless-stopped
    depends_on:
      - ros2-daemon
